DROP TABLE IF EXISTS `role`;
CREATE TABLE IF NOT EXISTS `role` (
    id INTEGER NOT NULL AUTO_INCREMENT,
    role VARCHAR(255) NOT NULL DEFAULT '',
    PRIMARY KEY (id)
) ENGINE=InnoDB DEFAULT CHARACTER SET utf8;
